import 'remixicon/fonts/remixicon.css';

import '@/styles/globals.css'

import Content from '@/components/content';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  'theme-color': '#161A26',
  'msapplication-navbutton-color': '#161A26',
  'apple-mobile-web-app-status-bar-style': '#161A26',
  'color-scheme': 'dark',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Content>
          {children}
        </Content>
      </body>
    </html>
  )
}
